# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'GitHub Pages'
description: 'GitHub Action to deploy to GitHub Pages'
author: 'crazy-max'
branding:
  color: 'green'
  icon: 'upload-cloud'

inputs:
  repo:
    description: 'GitHub repository where assets will be deployed (default current)'
    required: false
  target_branch:
    description: 'Git branch where assets will be deployed'
    default: 'gh-pages'
    required: false
  keep_history:
    description: 'Create incremental commit instead of doing push force'
    default: 'false'
    required: false
  allow_empty_commit:
    description: 'Allow an empty commit to be created'
    default: 'true'
    required: false
  build_dir:
    description: 'Build directory to deploy'
    required: true
  committer_name:
    description: 'Deprecated. Use committer input with crazy-max/ghaction-github-pages@v2'
    deprecationMessage: 'The committer_name input will not be supported. Use committer input with crazy-max/ghaction-github-pages@v2'
    required: false
  committer_email:
    description: 'Deprecated. Use committer input with crazy-max/ghaction-github-pages@v2'
    deprecationMessage: 'The committer_email input will not be supported. Use committer input with crazy-max/ghaction-github-pages@v2'
    required: false
  commit_message:
    description: 'Commit message'
    required: false
  fqdn:
    description: 'Write the given domain name to the CNAME file'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
